spring:
  application:
    name: user-service
  datasource:
    driver-class-name: ${sky.datasource.driver-class-name:com.mysql.cj.jdbc.Driver}
    url: jdbc:mysql://localhost:3306/forum_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${sky.datasource.username:root}
    password: ${sky.datasource.password:123456}
jwt:
  secret: "yourVeryLongAndSecureSecretKey12345678901234567890"
  expiration: 86400000